# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f528a426677ab41746b964e40d87fb430deedad2b521fbcb7844f0416b20169c343f9442b472bba4f186e37df7697064635b310a35aa5c28452caad832593fe7

test:
  secret_key_base: 6b1fa893dc7f47c9d12fc55415bc2ccf659470f0ff50992237649eb2ed3e0e67b96b6f74c588ee9aeaf432dc9118852cb446a6b186977e2aee9eea0d47056619

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
